### PR TITLE
Fixed preferences not interacting with storage

### LINKED ISSUE #36: Logic: Preferences are currently broken
### Before submitting an issue, please check the following

- [x] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [x] I agree to follow the [Code of Conduct](https://github.com/WayneKeenan/ClintonCAT/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Preference don't work

### To reproduce

...

### Expected behavior

...

### ClintonCAT version

0.0.0

### Platform

...

### Anything else?

_No response_

### LINKED ISSUE #37: UI: Toggle is broken
### Before submitting an issue, please check the following

- [x] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [x] I agree to follow the [Code of Conduct](https://github.com/WayneKeenan/ClintonCAT/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Toggle on/off is not working.
Depends on #36 

### To reproduce

...

### Expected behavior

...

### ClintonCAT version

0.0.0

### Platform

...

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Edgiest05**
Fixes #36.
Fixes #37.

With these changes preferences now actually persist in synced storage.
Notably I've reduced the moving parts in the `preferences.ts`, file making use of the single method `initDefaults` to achieve initialization and refreshing behaviors.

I'm open to any feedback and, once again, thank you for the amazing work you've been putting in this extension!

### CODE REVIEW

File: src/options.tsx [hunk 1]
```diff
@@ -35,6 +37,12 @@ const Options = () => {
         Preferences.domainExclusions.value = [];
     };
 
+    const onKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
+        if (event.key == 'Enter') {
+            addItem();
+        }
+    };
+
```
Comment (Producdevity) [inline src/options.tsx:45]: **suggestion**:
I personally think we are better off using a HTML form with an onSubmit handler for basic keyboard support like this

File: src/popup.tsx [hunk 2]
```diff
@@ -2,29 +2,33 @@ import React, { useState } from 'react';
...
+import ChromeSyncStorage from './storage/chrome-sync-storage';
+import ChromeLocalStorage from './storage/chrome-local-storage';
+
+Preferences.initDefaults(new ChromeSyncStorage(), new ChromeLocalStorage());
 
 const Popup = () => {
-    const [isEnabled, setIsEnabled] = useState(false);
+    const [isEnabled, setIsEnabled] = useState(Preferences.isEnabled.value);
+
+    Preferences.isEnabled.addListener('enable-options', (result: boolean) => {
```
Comment (Producdevity) [inline src/popup.tsx:13]: **suggestion:**

Replacing the string with `Preferences.IS_ENABLED_KEY`

Comment (Producdevity) [reply src/popup.tsx:13]: Oh my bad, I see that this key is used for something else. Would it be better to add keys for the events as static properties of `Preferences`

**Comment by WayneKeenan** [comment]
Thank you so much for this!

File: src/options.tsx (hunk 1 above)
Comment (WayneKeenan) [reply src/options.tsx:45]: I'd like to keep to Typescript

File: src/popup.tsx (hunk 2 above)
Comment (WayneKeenan) [reply src/popup.tsx:13]: Would you like to raise a PR for your suggestion?

File: src/options.tsx (hunk 1 above)
Comment (Producdevity) [reply src/options.tsx:45]: @WayneKeenan Yes, of course, but TS is irrelevant to following html semantics and standard. You can still use typescript while adhering to web standards
